coverage_service: coveralls
ci_service: circleci
xcodeproj: PubnativeLite/PubnativeLite.xcodeproj
scheme: PubnativeLite
workspace: PubnativeLite/PubnativeLite.xcworkspace
ignore:
    - "dependencies/**"
    - "circleci/*"
    - "PubnativeLite/PubnativeLiteDemo/*"
    - "PubnativeLite/PubnativeLiteTests/*"
    - "../*"
