coverage_service: coveralls
ci_service: circleci
xcodeproj: PubNativeLite/PubNativeLite.xcodeproj
scheme: PubNativeLite
workspace: PubNativeLite.xcworkspace
ignore:
    - "dependencies/**"
    - "circleci/*"
    - "PubNativeLite/PubNativeLiteDemo/*"
    - "PubNativeLite/PubNativeLiteTests/*"
    - "../*"
