version: 2
jobs:
    machine:
        timezone:
            Europe/Berlin
        xcode:
            version: 9.2

    test:
        override:
            - xcodebuild
                -workspace PubnativeLite.xcworkspace
                -scheme PubnativeLite
                -destination 'platform=iOS Simulator,OS=11.2,name=iPhone 7'
                clean test
                | tee $CIRCLE_ARTIFACTS/test_xcodebuild.log
                | xcpretty
                    -c
                    -r junit --output $CIRCLE_TEST_REPORTS/junit.xml
                    -r html --output $CIRCLE_TEST_REPORTS/report.html
                    -r json-compilation-database --output $CIRCLE_ARTIFACTS/test_compilation_database.json
        post:
            - bundle exec slather
    deployment:
        deployable:
            branch: /(development|beta|master)/
            commands:
                - ./scripts/generate.sh
                - ./scripts/publish.sh
